spring.application.name=okhrestaurant

spring.datasource.url=${DATABASE_URL}

spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.ssl=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
zenziva.userkey=${ZENZIVA_USERKEY}
zenziva.apikey=${ZENZIVA_APIKEY}
zenziva.brand=${ZENZIVA_BRAND}