spring.application.name=okhrestaurant
spring.datasource.url=${DATABASE_URL}
spring.datasource.hikari.data-source-properties.sslmode=require
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
zenziva.userkey=${ZENZIVA_USERKEY}
zenziva.apikey=${ZENZIVA_APIKEY}
zenziva.brand=${ZENZIVA_BRAND}
